language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '7'
  - '6'
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - npm i
script:
  - npm run travis
after_script:
  - bash < (curl -s https://codecov.io/bash)
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm i -g semantic-release
  - semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
